

services:
  postgres:
    image: postgres:16
    container_name: task_postgres
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: JOHNjohn$12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_user -d task_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: task_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: task_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://task_user:JOHNjohn$12345@postgres:5432/task_db
      REDIS_URL: redis://redis:6379/0
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped

  worker:
    build: .
    container_name: task_worker
    command: celery -A app.celery_config worker --loglevel=info
    environment:
      DATABASE_URL: postgresql://task_user:JOHNjohn$12345@postgres:5432/task_db
      REDIS_URL: redis://redis:6379/0
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  flower:
      build: .
      container_name: task_flower
      command: celery -A app.celery_config flower --port=5555
      ports:
        - "5555:5555"
      environment:
        CELERY_BROKER_URL: redis://redis:6379/0
        CELERY_RESULT_BACKEND: redis://redis:6379/0
      depends_on:
        redis:
          condition: service_healthy
      restart: unless-stopped
volumes:
  postgres_data:
